# Generated by Django 6.0.3 on 2026-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('makeup', 'Makeup'), ('dress', 'Dress')], default='makeup', max_length=20),
            preserve_default=False,
        ),
    ]
